[package]
name = "newt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
macroquad = "0.4.14"
num-traits = "0.2.19"
rand = "0.9.2"
rayon = "1.11.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
